namespace: default
resources:
  - frontend.yaml
  - backend.yaml
  - mysql.yaml
  - nginx.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - configs/init.sql
